    source "hyperv-iso" "autogenerated_1" {
    boot_command         = ["c  setparams 'kickstart'<enter> linuxefi /images/pxeboot/vmlinuz inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks_fedora36.cfg<enter> initrdefi /images/pxeboot/initrd.img<enter> boot<enter>"]
    boot_wait            = "5s"
    communicator         = "ssh"
    cpus                 = "2"
    disk_size            = "20000"
    enable_secure_boot   = true
    generation           = 2
    guest_additions_mode = "disable"
    http_directory       = "./"
    iso_checksum         = "725e1d56d8bcb935f0398dfd430996bea528f46a"
    iso_url              = "C:\\lab\\distr\\fedora36.iso"
    memory               = "4096"
    secure_boot_template = "MicrosoftUEFICertificateAuthority"
    shutdown_command     = "echo 'packer' | sudo -S -E shutdown -P now"
    ssh_password         = "vagrant"
    ssh_timeout          = "4h"
    ssh_username         = "vagrant"
    temp_path            = "C:\\lab\\VM"
    vm_name              = "fedora36"
    }
    build {
    sources = ["source.hyperv-iso.autogenerated_1"]
    post-processor "vagrant" {
    compression_level = 0
    }
    }